# This workflow reads its configuration from the .github/labeler.yml file.
# This workflow and its configuration can be deleted once the website's feature branch is merged.
name: "Pull Request Labeler"
on:
- pull_request_target

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v5
